--- 
- block: 
    - name: generate parameter overrides 
      set_fact: 
        cf_parameter_overrides: "{{ cf_stack_inputs | dict_to_kv_string }}" 
    - name: deploy stack 
      shell: aws cloudformation deploy 
        --stack-name {{ cf_stack_name }} 
        --template-file {{ cf_stack_template_yaml }} 
        {{ '--s3-bucket ' + cf_s3_bucket if cf_upload_s3 else '' }} 
        {{ '--s3-prefix ' + cf_stack_name + '/' + current_timestamp if cf_upload_s3 else ''}} 
        {{ '--parameter-overrides ' + cf_parameter_overrides if cf_parameter_overrides else '' }} 
        {{ '--role-arn=' + cf_stack_role if cf_stack_role else '' }} 
        --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND 
        --no-fail-on-empty-changeset 
  tags: 
    - deploy 
 
- block: 
    - name: get stack facts 
      cloudformation_facts: 
        stack_name: "{{ cf_stack_name }}" 
        stack_resources: true 
      changed_when: false 
    - name: set stack facts 
      set_fact: 
        Stack: "{{ Stack | combine({'Facts': cloudformation[cf_stack_name]},recursive=True) }}" 
    - debug: msg={{ Stack.Facts }} 
      when: debug 
  tags: 
    - deploy