---
- block:
    - name: set template encoding facts
      set_fact:
        cf_stack_template_yaml: "{{ cf_build_folder }}/{{ env }}-{{ cf_stack_name }}-stack.yml"
        cf_stack_policy_json: "{{ cf_build_folder }}/{{ env }}-{{ cf_stack_name }}-policy.json"
        cf_stack_config_json: "{{ cf_build_folder }}/{{ env }}-{{ cf_stack_name }}-config.json"
    - name: generate YAML template
      template:
        src: "{{ cf_stack_template }}"
        dest: "{{ cf_stack_template_yaml }}"
      changed_when: False
    - name: load generated template
      include_vars:
        file: "{{ cf_stack_template_yaml }}"
        name: cf_stack_template_vars
    - name: merge template into Stack variable
      set_fact:
        Stack: "{{ cf_stack_template_vars | combine(Stack, recursive=True) }}"
    - name: apply stack transforms
      set_fact:
        Stack: "{{ Stack | stack_transform(debug=debug, template_paths=[role_path + '/templates'], filter_paths=[role_path + '/filter_plugins']) }}"
    - name: merge stack globals
      set_fact:
        Stack: "{{ Stack | combine({ 'Resources': Stack.Resources | dict_override(cf_stack_globals)}, recursive=True) }}"
        cf_stack_template_vars: "{{ cf_stack_template_vars | combine({ 'Resources':cf_stack_template_vars.Resources | dict_override(cf_stack_globals)}, recursive=True) }}"
    - name: apply simple stack overrides
      set_fact:
        cf_stack_template_vars: "{{ cf_stack_template_vars | combine(cf_stack_overrides, recursive=True) }}"
    - name: apply complex overrides
      set_fact:
        Stack: "{{ Stack | combine(vars['hostvars'][env] | stack_overrides, recursive=True) }}"
    - name: apply stack property transforms
      set_fact:
        Stack: "{{ Stack | property_transform(filter_paths=[role_path + '/filter_plugins']) }}"
    - name: output stack
      copy: content={{ Stack | stack_output | to_nice_yaml(indent=2) }} dest={{ cf_stack_template_yaml }}
      changed_when: False
    - name: generate stack policy
      copy: content={{ cf_stack_policy | to_json }} dest={{ cf_stack_policy_json }}
      changed_when: False
    - name: set stack inputs
      set_fact:
        cf_stack_inputs: "{{ cf_stack_inputs | default(Stack.Parameters | default({}) | stack_inputs(Stack.Inputs | default({}))) }}"
    - name: set stack config
      set_fact:
        cf_stack_config:
          Parameters: "{{ cf_stack_inputs }}"
          StackPolicy: "{{ cf_stack_policy }}"
          Tags: "{{ cf_stack_tags }}"
    - name: generate stack config
      copy: content={{ cf_stack_config | to_json }} dest={{ cf_stack_config_json }}
      changed_when: False
    - name: detect template size
      stat:
        path: "{{ cf_stack_template_yaml }}"
      register: cf_stack_template_stat
    - name: set upload flag if template exceeds 51,200 bytes
      set_fact:
        cf_upload_s3: True
      when: cf_stack_template_stat.stat.size > 51200
  tags:
    - generate