--- 
- block: 
  - name: obtain account id 
    shell: aws sts get-caller-identity 
    changed_when: false 
    register: cf_aws_identity 
  - debug: msg={{ cf_aws_identity }} 
    when: debug 
  - name: set aws account fact 
    set_fact: 
      cf_account_id: "{{ (cf_aws_identity.stdout | from_json).get('Account') }}" 
  - name: set s3 bucket fact for account id {{ cf_account_id }} 
    set_fact: 
      cf_s3_bucket: "{{ cf_account_id + '-cfn-templates' }}" 
  when: cf_s3_bucket is not defined 
  tags: 
    - deploy